[tools]
node = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
python = "3.13"

[settings]
idiomatic_version_file_enable_tools = ["python", "node", "npm"]
#minimum_release_age = "7d"
#minimum_release_age_excludes = ["npm:@openai/codex", "npm:@anthropic-ai/claude-code"]
